version: "3.8"

services:
  web:
    image: httpd
    container_name: dio_apache
    ports:
      - "80:80"
    volumes:
      - C:\Projetos\dio\dio-docker-apache\front-end:/usr/local/apache2/htdocs
      - C:\Projetos\dio\dio-docker-apache\front-end\httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - apache-net
  api:
    build: ./back-end/
    container_name: api
    ports:
      - "3000:3000"
    networks:
      - apache-net
  db:
    image: postgres:14-alpine
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - C:\Projetos\dio\dio-docker-apache\db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "senha123"
      POSTGRES_DB: "dio_apache"
    networks:
      - apache-net
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - apache-net

networks:
  apache-net:
    driver: bridge
